### PR TITLE
allow $DOCKER_HOST to be passed to docker --host

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by jberkus** [comment]
Hey, can you resubmit this to zalando/patroni?  That's their dockerfile, this is just my fork of the main patroni project, which is zalando/patroni.

**Comment by drnic** [comment]
Yeah will do. Sorry I found this repo after seeing one of your talks on YouTube (10 mins to replication).

Ultimately I started my own dockerfile & bootstrapping scripts for our own use case: but I will repost the PR upstream.

Thanks

**Comment by jberkus** [comment]
Can you share your docker file somewhere?  I'm about to put up my docker-compose setup as a separate project.

**Comment by drnic** [comment]
Yep, currently it is at https://github.com/cloudfoundry-community/patroni-boshrelease/tree/master/images and the readme documents (hopefully) a walk thru tutorial. It's a WIP as I just started playing with wal-e today.

**Comment by drnic** [comment]
I borrowed ideas from https://github.com/zalando/spilo/tree/master/postgres-appliance too

**Pull request closed without merging**
